"""Code generation — produces runnable analysis script."""
from __future__ import annotations

from typing import List

from pharmforge.rag.store import RetrievedDoc

TEMPLATE = '''"""
Generated by PharmForge CodeGen
Query: {query}
SMILES: {smiles_list}
Molecules cited: {cited}
"""
from rdkit import Chem
from rdkit.Chem import Descriptors, Crippen, QED, AllChem, DataStructs
from rdkit.Chem.AllChem import GetMorganFingerprintAsBitVect

SMILES = {smiles_repr}

def analyze():
    results = []
    for smi in SMILES:
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            print(f"INVALID SMILES: {{smi}}")
            continue
        mw = Descriptors.MolWt(mol)
        logp = Crippen.MolLogP(mol)
        qed = QED.qed(mol)
        tpsa = Descriptors.TPSA(mol)
        # Fingerprint
        fp = GetMorganFingerprintAsBitVect(mol, 2, nBits=2048)
        print(f"SMILES: {{smi[:40]}} | MW={{mw:.2f}} LogP={{logp:.2f}} QED={{qed:.3f}} TPSA={{tpsa:.1f}} BitsOn={{fp.GetNumOnBits()}}")
        results.append({{"smiles": smi, "mw": mw, "logp": logp, "qed": qed, "tpsa": tpsa}})
    # Pairwise similarity if >=2
    if len(SMILES) >= 2:
        # Compare first two
        m1 = Chem.MolFromSmiles(SMILES[0])
        m2 = Chem.MolFromSmiles(SMILES[1])
        if m1 and m2:
            fp1 = GetMorganFingerprintAsBitVect(m1, 2, nBits=2048)
            fp2 = GetMorganFingerprintAsBitVect(m2, 2, nBits=2048)
            sim = DataStructs.TanimotoSimilarity(fp1, fp2)
            print(f"Tanimoto similarity (0 vs 1): {{sim:.4f}}")
    # Conformer demo for first molecule
    if SMILES:
        mol = Chem.AddHs(Chem.MolFromSmiles(SMILES[0]))
        if mol:
            params = AllChem.ETKDGv3()
            params.randomSeed = 42
            cid = AllChem.EmbedMolecule(mol, params)
            print(f"Conformer generation: {{'success' if cid==0 else 'failed'}}")
    print("Analysis complete.")
    return results

if __name__ == "__main__":
    analyze()
'''


def generate_script(query: str, smiles_list: List[str], docs: List[RetrievedDoc] | None = None) -> str:
    """Generate runnable analysis script for given SMILES. Deterministic, no LLM required."""
    if not smiles_list:
        # Fallback to aspirin + imatinib as demo
        smiles_list = ["CC(=O)OC1=CC=CC=C1C(=O)O", "CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C)NC4=NC=CC(=N4)C5=CN=CC=C5"]
    # Sanitize smiles_list — ensure valid python repr, keep 1-5 entries
    smiles_list = smiles_list[:5]
    cited = ", ".join(d.id for d in (docs or [])) or "N/A"
    return TEMPLATE.format(
        query=query.replace("{", "{{").replace("}", "}}"),
        smiles_list=", ".join(smiles_list),
        cited=cited,
        smiles_repr=repr(smiles_list),
    )


# Optional LLM-backed generation (mockable) — not required for tests
def generate_script_llm(query: str, smiles_list: List[str], docs: List[RetrievedDoc] | None = None, llm_call=None) -> str:
    """If llm_call provided, use it; otherwise fallback to template."""
    if llm_call is None:
        return generate_script(query, smiles_list, docs)
    try:
        prompt = f"Generate RDKit analysis script for query: {query} SMILES: {smiles_list}"
        out = llm_call(prompt)
        if out and "Chem.MolFromSmiles" in out:
            return out
    except Exception:
        pass
    return generate_script(query, smiles_list, docs)
